In [16]:
#First reading the data
import numpy as np
import pandas as pd
data=pd.read_csv('Salary Data.csv')
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print(data)


     Age  Gender Education Level                      Job Title  \
0     32    Male      Bachelor's              Software Engineer   
1     28  Female        Master's                   Data Analyst   
2     45    Male             PhD                 Senior Manager   
3     36  Female      Bachelor's                Sales Associate   
4     52    Male        Master's                       Director   
..   ...     ...             ...                            ...   
368   35  Female      Bachelor's       Senior Marketing Analyst   
369   43    Male        Master's         Director of Operations   
370   29  Female      Bachelor's         Junior Project Manager   
371   34    Male      Bachelor's  Senior Operations Coordinator   
372   44  Female             PhD        Senior Business Analyst   

     Years of Experience  Salary  
0                    5.0   90000  
1                    3.0   65000  
2                   15.0  150000  
3                    7.0   60000  
4                   

In [17]:
#Second preprocessing on data: (Cleaning, Encoding, Normalizing, and feature engineering, and balancing 'in classification case')
# 1. Cleaning data 'handling the null values inside data' 
a=data['Salary'].unique()
b=data['Job Title'].nunique()
print(b)
#After checking the unique values inside each colum we found non 'Null' values to handle

174


In [18]:
# 2. Encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#Frist applying 'label encoder' for binary encoding
x[:,1]=LabelEncoder().fit_transform(x[:,1])
x[:,3]=LabelEncoder().fit_transform(x[:,3])
#Second applying 'OneHotencoder' for multi categorical classification
from sklearn.compose import ColumnTransformer
hotencoder=ColumnTransformer([('encoder',OneHotEncoder(),[2])],remainder="passthrough")
x=np.array(hotencoder.fit_transform(x))

print(x)

[[1.0 0.0 0.0 ... 1 159 5.0]
 [0.0 1.0 0.0 ... 0 17 3.0]
 [0.0 0.0 1.0 ... 1 130 15.0]
 ...
 [1.0 0.0 0.0 ... 0 70 2.0]
 [1.0 0.0 0.0 ... 1 137 7.0]
 [0.0 0.0 1.0 ... 0 110 15.0]]


In [19]:
# 3. Normalizing
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x[:,0]=np.ravel(ss.fit_transform(x[:,0].reshape(-1,1)))
x[:,4]=np.ravel(ss.fit_transform(x[:,4].reshape(-1,1)))
y=np.ravel(ss.fit_transform(y.reshape(-1,1)))
# 4. Balancing "we won't need it because we use 'regression' here"
# 5. Feature scalling for linear SVM


In [32]:
#Start in applying model
#Split your data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.20,random_state=0)
#Start SVM regression model
#'SVR' it means support vector regression
from sklearn.svm import SVR
#'rbf' is the function used for kernel trick used for splitting the data
regressor = SVR(kernel = 'linear')
regressor.fit(x_train,y_train)


SVR(kernel='linear')

In [35]:

from sklearn.metrics import r2_score
#testing on a prediction
# Make predictions on the testing data
y_pred = regressor.predict(x_test)

# Evaluate the model using mean squared error
acc = r2_score(y_test, y_pred)
print('accuracy is:', acc)

#print(accuracy_score(y_test, y_pred))

accuracy is: 0.9004386988944044
